# Feature Engineering

In [29]:
# Import Libraries
import pandas as pd
import numpy as numpy

# The preprocessing module contains tools to prepare data before training a machine learning model.
from sklearn.preprocessing import LabelEncoder  # this library help to convert categorical column into numerical column
from sklearn.preprocessing import StandardScaler # It scales numerical values so that all features are on a similar scale.

In [ ]:
# Load Clean Dataset
df = pd.read_csv('../data/train_clean.csv')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S

In [9]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Embarked'],
      dtype='object')

In [12]:
# Drop Unnecessary Columns
df = df.drop(columns=['Ticket','Name','PassengerId'])
df.head()

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

In [ ]:
# we need encode Sex column to train machine learning model
df['Sex'].value_counts()

Sex
male      577
female    314
Name: count, dtype: int64

In [ ]:
# after encoding 
encoder = LabelEncoder()
df['Sex'] = encoder.fit_transform(df['Sex']) # LabelEncoder assigns labels alphabetically so Female → 0, male → 1
df.head()

   Survived  Pclass  Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    1  22.0      1      0   7.2500        S
1         1       1    0  38.0      1      0  71.2833        C
2         1       3    0  26.0      0      0   7.9250        S
3         1       1    0  35.0      1      0  53.1000        S
4         0       3    1  35.0      0      0   8.0500        S

In [ ]:
# now we do same for Embarked
df['Embarked'].unique()

array(['S', 'C', 'Q'], dtype=object)

In [19]:
# encoding for embarked column
df['Embarked'] = encoder.fit_transform(df['Embarked']) 
df['Embarked'].head() # where C → 0, Q → 1, S → 2

0    2
1    0
2    2
3    2
4    2
Name: Embarked, dtype: int64

In [23]:
# check datatypes 
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  891 non-null    int64
 1   Pclass    891 non-null    int64
 2   Sex       891 non-null    int64
 3   Age       891 non-null    float64
 4   SibSp     891 non-null    int64
 5   Parch     891 non-null    int64
 6   Fare      891 non-null    float64
 7   Embarked  891 non-null    int64
dtypes: float64(2), int64(6)
memory usage: 55.8 KB

In [ ]:
# Machine learning models often perform better when numerical features are on a similar scale.
numeric_columns = ['Age','Fare','SibSp','Parch']

In [ ]:
# Creating the scaler
scalar = StandardScaler() # It transforms values so that:
                          # Mean ≈ 0
                          # Standard deviation ≈ 1

In [ ]:
# The relative differences remain, but the scale is standardized.
df[numeric_columns] = scalar.fit_transform(df[numeric_columns])

In [27]:
df.head()

   Survived  Pclass  Sex       Age     SibSp     Parch      Fare  Embarked
0         0       3    1 -0.565736  0.432793 -0.473674 -0.502445         2
1         1       1    0  0.663861  0.432793 -0.473674  0.786845         0
2         1       3    0 -0.258337 -0.474545 -0.473674 -0.488854         2
3         1       1    0  0.433312  0.432793 -0.473674  0.420730         2
4         0       3    1  0.433312 -0.474545 -0.473674 -0.486337         2

In [ ]:
# Save the Processed Dataset
df.to_csv("../data/train_processed.csv", index=False)